version: "3.8"
services:
  db:
    image: postgres
    volumes:
        - "./data:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: lil_post
      POSTGRES_PASSWORD: postaroo
      POSTGRES_DB: opendiscourse
    command: ["postgres", "-c", "log_statement=all"]